name: CI Pipeline

on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
        
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: test  # This job runs only if the "test" job succeeds

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
  
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
  
      # Step 4: Build the app
      - name: Build the app
        run: npm run build
  
      # Step 5: Upload build artifacts (optional, for debugging or archiving)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/  # Adjust this path based on your project's build output
  
      # Step 6: Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*  # Adjust to match your build output
          tag_name: v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}